-- V3.5 - eseguire UNA SOLA VOLTA sul database D1 collegato al progetto
ALTER TABLE centers ADD COLUMN favicon_url TEXT NOT NULL DEFAULT '';
ALTER TABLE centers ADD COLUMN services_text TEXT NOT NULL DEFAULT '';
ALTER TABLE centers ADD COLUMN cancellation_rules TEXT NOT NULL DEFAULT '';
ALTER TABLE centers ADD COLUMN custom_domain TEXT NOT NULL DEFAULT '';
ALTER TABLE centers ADD COLUMN parking INTEGER NOT NULL DEFAULT 0;
ALTER TABLE centers ADD COLUMN showers INTEGER NOT NULL DEFAULT 0;
ALTER TABLE centers ADD COLUMN lighting INTEGER NOT NULL DEFAULT 0;

ALTER TABLE bookings ADD COLUMN block_category TEXT NOT NULL DEFAULT '';
ALTER TABLE bookings ADD COLUMN block_group TEXT NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS customer_notes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  center_id INTEGER NOT NULL,
  phone TEXT NOT NULL,
  note TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(center_id, phone)
);
